apiVersion: v1
kind: Service
metadata:
  labels:
    app: extruai
  name: extruai
spec:
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: extruai

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: extruai
  name: extruai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: extruai
  template:
    metadata:
      labels:
        app: extruai
    spec:
      containers:
        - image: "ghcr.io/c0c0n3/kitt4sme.roughnator:latest"
          imagePullPolicy: IfNotPresent
          name: roughnator
          ports:
          - containerPort: 8000
            name: http
          env:
          - name: "ORION_BASE_URL"
            value: "http://orion:1026"
