apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: fams-image
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgAN2vgLd/sZnWBpFsGI2olRlk6gpkINCYSiiz2svxMyGY74L9GKYWVnQu+nPpdgPtMY3pIlpMnyVFzqKc1HpbkyFgrk2vhFLc+kD+ynok8dLb2Ux49QifYLXTQHrzZk4ii6KIpDwuPESHNovrInLgP9xEqFAa3s3Yy0tei4a2PfFXL3I3Kdp/UAfElgS/Vp4rz0WM11aWLZiODvrEyxVMuwrL7QkvbrD2UPNEfdHh6vLq02NpPyjm9ufV23CKDeZLOm3Zrq/pvBfS2Uza/V2ZYeXjaUVOy8vjRYA0cX0wWuLbFV5Ww0muNNc/5deFXioOZf8ewGACka9FmhHegg+pXcqBeVg1gOV2Oh3NvM5p84Qz7D2M39AQ1RtzUn3r+zZZV/Q2UeW80fKy9cxkSfNJk8KNoHUsxmfn+7kgSQJuFOpJyf7m40iCObaMgtP9mJBajYu5Z1sBJ5PXDWh27YW1sCoVPi68d1oDSXiNuPYcpimANzGbOyV3d8t7AC7sS3GyfQrg1RToEIV5XFTvIPRKlyfrvbCQLInJ2/Q8jQOo7HeM8GlbeKHS8m6WD/DjJPweJBb/kiNtMa9+Vp/VylLdndLT/IgPP/A2JGIc65IeM7zz+mDEXQPLZoHtuFKyxPj5c5I70ChafOYBmHj5lyL3aIOat7x2aEE37PO1LK5lSXVeTC46+hsSFQ/f8SEj88+1YUoAc3WSlTg3X/n38zaSGe2sYKBl36McYNVb2vh+Nx/kHFuYF2qicnVjf/RwudRQohV0GYl243rYZOEo2QoxKu+HFuH7Eg19bvgO3+MfDT+jDR8LXcRx6Lm9T0uKf7x3mLs8xYLZ08DuCI8V0hNVZLXwG7PtnVHLTy4faCu6KriOqLTE8qfZHqTbhJPHmOCFz92pLGjeQcbZj/
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: fams-image
      namespace: default
    type: kubernetes.io/dockerconfigjson

