apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-builtin-admin
  namespace: default
spec:
  encryptedData:
    password: AgCvBKwgsr3MnEgWDdUQJdR7q7nfJp5APlA/pxGb50CEEaqiI7+1GROu7uArjtbJ+vAEW9qfiDXBZBxF/4j9NaDZz/MiQ0ceP/emR0t1k1/PaMZFeXqv0pqfxEyjHI+Uk1d+yBZ7C4KSG9UPAuZyDuvBkXqCEXSMspg83lcCeHBviRVHzENJucz140Yme/3M33IH6P5J/nj7dsO8wB+CKnSPH/04/Rvj2tvOS4j9zVaDMcaGenG1nGk6IXRGFOQv+GRqXkCY0hTUAsY4KasGEcLptnbHAmpOpEEIZB6XH4RGJtrkLrZgXCQJ9cmaSoDGQQL42+sK74XB99ueWTOZv3oDS8LuUGodLtfcgIXwmOZ3R76kLuilz5yGd70+zpzEPsL2haiWAtE7EcKCIDBGdFZzLsbY1EbXc3D9otORjWX5Ctm1CeHOENLQuptwZ/1MmKGk+4TcRSez6EkMe8zlX8qgdDtm7FWy780ONuxcoNzIXO/Q4QBlTP8BeeJ74UxQ/WXQjH7RIhh6YJPLv+kR005uvXApSivkGjvHGq+0XYvlPqjZpwDaZyO85IvgOj/Yv7tmgdRknb4BBdWpW+sdwZok/4rWaPDwb/mdxUrMQz6Nt87D4fKdKBqIuO6gRnxNao/2zww312MAD9Uf7cpHPjIF549kNVdnF9kIKSfINafIG6vSApGVCtEZZ6VsHWiMwOzxOcKFytfrBRFlmtWIvlEscUhCf2TsLAQj8gI=
    username: AgC29XWr4L+hcZeHxv4OO6hhosT0xE8/6qn3r1lbsKIhaRyskz3EX742v5gNE55ESWjX7tDZhdLMt2FB0N90ztv488Jj6xVlMJYu/2j+FjP3Y41GZuV2odArmFvX12xb2ii1cDxVNMSsDfSUEib2rOsOKkWKJMWsO/t4aGolniQolDt16A8C4X/8eTuwfgEeajDuCX3y/eIte+xEZFtz42Hn2Dioj2YREAJ/iRyQ1s6HmRZ+Ei55yydPkbwqr4VSu76fQw9yERwAIqk7Cht/V64vQCsLMk7kv0Zd4tmioOX4d9wwqq27eNP7YG3qt4O+lyYmSuY+fVIOT9x2Lb77f9b7cAdynBLczcKOB9xF5Y14IsoObz8W07NETQlBYnIQH1DBCFGmEVqpsDe6S75c9bYT5wWNmuTscb3nEiUh4VChy1fM50o0Bpdrsmvirz068IcM8r1UyvXKkDZfOc3Ha9C54dhb5+jdpjetVDmMwwURZklkCwQoxzTQz6gr1kyM9d/ejdwoF0c2h/F+0VzR0a78MOHdvMh5l0zfubpMQhmpWHyxP7oRTYhl2q4i5Xp+OM2LFLNMm5DaccMxsKIXZKbVdpvvi3+0qabLExRBdgTytDqeK2ZWtyvnZKy50L3kyVhIMdZ+ftyGV4iWYugYDQ9VrOJAmqE0NACW1McSHWj+M7orWO3IUOxBEn053CI2Kozfx0HVTQ==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: keycloak-builtin-admin
      namespace: default
    type: Opaque

