apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-builtin-admin
  namespace: default
spec:
  encryptedData:
    password: AgAMzwdKY7X0t0LEE6UaZ5ecUZwSivxHjra08D+O6+w+w82pOxFZF1387/TZyg7/jmEj5u51D7Dp6rcSuK3orch0VSi7cbC4KEra+QztU+6xu1xa/fmByH0EdFQNHypj1QFO9GdaEfq4TgJ38aKYR9z6pWkHCca8aaj+iF9HS0s+1Awai277/ZMF6AeGOIcf3iFxioO0QZ11VKDZuNY/KflM7XXAoPgRJJceQQtpphptMvLOKkbUNMfMPyMj0UQbKze+P494qHCkegbfu0HZk404mavPhZpYyYHa+ZuvggDQgn5ueNP42GP5AAb30PSzjylA4OJ0klL5RT1w8a7zCnT6DAvLFPwWyhehTqZzcBap8oDkVs4Wu2U57MnD4bUmY45ZsYHr8OgtT4N9c8cMuImhY9LunxTSRYFY7S2YES5mfDKfEfoR0wXoVxS8/ng6xOF0Ou2aYcYbW4gabyCn/+bkIK/k+lruqAUXXUwwNeJW1pQewUbBFZ4WvoO6H/FM+dMhIk5HEh22fvm288dXw789CVYQoqVepP7Lx2DYtkDVOHxVY1f7EPxnXFDU1kb8XUGCOHEkhkt+ULmgdxJ3Kr6nZBgpnq1mlJ71DqNexA7H9tsye2M0V0+f20LmWmGKL4xN5SidQxWHjeFfT/w8eCr+pSwyHbuhiK9+c8eTXJIPMp4wHwed5sqE3dyUrZIyyolF0oq9T6yVB3joSmbn2SjBnRR1xUP0cVX5A4c=
    username: AgAel5S3PQrJEwzlpUEFe18gNbdYNM8WQjjCZuhf/V6wIiBQp+FeVLZDjwHo4m0yTTBTkkdDv5ULSa2lyXCzDS3LtNmh8lc56kBW6HDqNyzwr6aNbC1Jz/C6js7ZYydQTtVpySr1MF/+8Y06lGUJlvISDMgd0TfnllfjYlBkE5AVxWnsdOyfCM1AwRSg5CCQ2kjKrBZmHaWKvbiCvjLRxn0jMtxBgLuN4kPYFFXSeXqN+P4mM/WgbBiDr+u7yHWLGS3SmPLSxyGqeunzfGDxvkGA1BO0EPyP5VWINKbjCdR3w00LvIX15TIEanF9K3ejDtwbsB5/xpfbyiELdVZ24TNNIyvCHxtNB8ZABcVYItxIoRNBPb17xYsnhjp4pgY4EMR8yTuROnjx+JUE4uBsF1PQwsIxto5cOUstMkMre58NacFDJIq9NKKv+Wwgep0Neb28xP9MzgIh3L1aElGyQt3ueAw8iwwisyBzUBDYAmDpH+aKOC36AiBFgJeMr1J3sTiNY/NmAn7lybnk1bH2djsregjzcKaoKmwg0QAOHyAsH9RNWqhVtrZ5wzDk8k0UTZLj3WMYg3Cc9D0zomHI7HY610TLGOLc+nsXZjwFKcAwJ2LKTPzZiM01WaHld+1AuvtTATLK2kKMEJJDJon8nrQ/ndCS32ixNB4cm9X97mpSZoMxC0zmt8CytjlDq4sWmjNebPQuww==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: keycloak-builtin-admin
      namespace: default
    type: Opaque

