apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mosquitto-passwd
  namespace: default
spec:
  encryptedData:
    passwd: AgAOK2Z78zttCLH0eUEk8Fo5KYyUiIH8Q1hfi482ongnHBkCRGAk7xI0/7HywxuDOL7BMn5G93BIQ5fewGpPNEbI9zZe6Kx1Dda+2RrnmE+FgdX2lvR7esjWOs6DqkbSx6aWnHSjBRuoKDvk0utWtCaZWjL8nYmsRMrcMJsR7v7Aa4uxmWPgB0PNTKrYKOs2RAs3sufoB7WRPyK3SYa11YmM+cVPhg3liigAlSMvVoMev9JPb6FxhTQKQ5OtjbZeVCuDEohI1N9Cqye5nt/q0nEJxm0mhOhOWieoNiq/tMias5GqP+A5ABkQ9W3WzSH8vMQXfoAckpwzyKBbwaN+oSdKCb/tqVNG/j5l/ogZ30E8v7n+zPQWmEfBYbTVwgpHAVlmFQ4UqzyLA++oQmgp3JGxoTcEcpumgQqrjG0+7z/5FoVDBBg4WwrF8ftqnE668XYZScXlTsByTXCerCv4TMH7ASxqLa5ZKCr/lT8JJ+PMHIKFprXUc/V40CLRaZNmkjoZIqlFns/i4xAgLV/7/gVPlYYkuzdMWdbFYG1yIwmGCzdrmItDHg7uHSkKHO2dra40Hs5X+cpeDK4cMBU5Blumvx03b8rtUs5MAGJWQCCfIsYpg2ix7syowsDNPKJczqQgA6iv3OdbHI0Ud229qO899YvSH4FxKrg/jg42JpKZQil9dBD2dzGEFZIVqbM/LHTN3eDvnfOlA1Dn82B7v3ao6+U/+bHzSF6koifUNaeSVTfu6rkNW0yU0kpTjSAJuy2FcoSnNHI531gei6KQe1vmI7nbGJiPZ0xrGuFswydPuDvbQdtcaBIsqiTZ76Bb5Z9Qkk5lHT1lFTc6wg81IoMLippDWUs=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: mosquitto-passwd
      namespace: default
    type: Opaque

