apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mosquitto-passwd
  namespace: default
spec:
  encryptedData:
    passwd: AgDnCsnYMVtyuChtNpzPdSY4wqm4xTSU+cD0QAqu45gY5D7ggsC8Px6fmcICQ8XH8WekYaVoi3zt+po1OA5pEt/YlMtanrJo4lO4cl0NWLF7WrfhC1LUWaKLDUZ/AZaP8y32seuN3hk7iM4onCQnJFbOrg3bRwCv3xFdblC4/e8hrwtcZdP9Nhq1Txw/8b4cxaBDtEzNe3QvbJgjzCL4/fZdPO+2Pl0Jmy+KTmQHnoK3BSAxZIW2vMbiO6OZ0K8beV0Qn7LB4LfB6I5ddQNkAS78fLadBUZVZKb8JdKJo1mYhdHpUqNKmndJuH8jhR4Ds5ju3QM3RAAdHLY8gFHNVrJo8u4jARC+zpl3jKWz2rAg+KKRgjvKxf9M3BR+UH4ATLPqyJ/rtnj38SqTd6DdZYP1TOFZWPK3pfewHepEbhDeWwsdWiP7aj83mhb3rZz9aXRg5WRLmRBwtUdR5A734qIi7MgS2pb9rH51qh5vM967ehB122xegITjSfEezRghoPCP4wjz2UEY8KPuEyCQVGkp8NYBv8xrtBcvx4lFba4FSkXCGVnUhppnwn6Fdb7PxHieipRlA0KGspc7GP4aZMbLLl1nwcRH8Ysygq+CqNiiwkASJn+wu5ST7fLl0bMS7n27HjYpqohXouOQZIMk/YHg7ZF9oGEiqBAVRAXeO+Z9xLq820Orb15ntpx1WvupcvhFP+Mm3YI/lLafiVdg7rxnVe0/4ZQjUIGE2YInP9RQVjLHCOuqKWZXeFp0mkxhnTepxp11M1LcMoFI9BMP2YmtjOB3NhSKSGazXFmO/CXYPkQC2r06HMinsIhi332l8bsFvz2D2m8rreWo+5iZufZhAmuP00o=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: mosquitto-passwd
      namespace: default
    type: Opaque

