apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-users
  namespace: default
spec:
  encryptedData:
    postgres.password: AgBExmLqbPV16BGM6K0P7saQEaGAM26Y6SjjtbqXk6a2ujABTjnZegiiOOG0ubgcbhL9q3CWyzV4gOUFoIRpbEd+PROGgHzX/xxEVPCEJBBifxhP67n9XyxsSt71LEQiNq5vD1odbZyXo+GKeuuaXjMcHgkZpsUwWR6lMZ4Z6+qj3juxqx26IGtIUPZ2PMWT9HcreztxP69EPuUxLBN4Vq1ZKcuJ/wlOEJjHQ0oIVS8hVnEC06/5uKey+UeKhAwVx8OkTNO+MOT/1oIjIv8iFZI9xkkFBsQ/Hw8YoLWF7cXsL/z1qdBQtyNmPCCRgUOd/Hk5pBr0ssOOvhetLrPCxzAjsLjhZ1PngY7igdgpevmlrokoTSzMG9yG/90vjPR6SydGiY3j19SiySb/AWl/WevfIhQdJyedij5pMOzBD23GKYgxYacVX+zGuVeezu5E1qQmGmc82yoI15y3oyYItnLGbFcYQfQyQVHU6JvjWgT5MhApuzm7ae81R48nA3vxdxoXGTAMwLx5XBEmc37H/sWbd5r6jKJLlPULOsUnIbv4N3yjqm/C3UPlHlOHn/vJ3s2DjWnAwOiJiSZ+2ZlsUOc1xLmUwxj5q8QfUlrQI8B9lE4alS/ZZpf05sll3/4OEHbvJitXbZEeHWda4qsxtmWoxXpM3nKnB2hp4ZXjXcG86z+yylK0zBaY4YFPYZZ7yzAgwzEM+IecJzPxUn+IR4hRtMjWIdK1Zx5qtac=
    quantumleap.password: AgC5m39ahsOw2YDz0dRKbeg0Vbx/0bzj9k6OYWUwtqfUArbFx+6CDMkinIVk8JWOesXMU66xSrKJGDf5SEsI9sfjfREdaFm4RaEzdtiGMjvw90Hiqt85Qz7kH1q1UQqZnCoLzaCR2r4QTafohG4Iu+DsKhSqZdgDFPTuYFhwbGS/QHarX0yAeDSyOnFj8q8bnhyK5N152NyL8Z7XlG5zoFZxZqJNr9xD868sXT8RxqAkV+kqKnN3SO7ZcTCBCZYgD+a0Hl7/2bnQHEftIwKvSPsDSABYOYJ3WVreocxTT2ASqIf9C1v5asnmMb9iAkNmFmtOdFOrhS364WLb1igksb46aEOLktxZfxbb94GrQKn/EJunGV/+uWhIzvtV66aIyCzkQMZj/xLJZ6O+HFSY31Y/4LnqikA/FTrsnewetvJVjNmiNnFwTIRPpuEyvrsD7k+hs/i7wBqphXu7p9dSMwuzRHOkHROL4eJFqE2mW0mN6H7i+BSGGnamzHmidC2ZE2wt4oBJaZcP2wASRbcj1Zv1S3tzdCz/13x+eyXxyAj4olZ5LTCmEdEFFfnuOkiXi6X+X/VtWGIrd6gds6Ih4uoqC+fULuhmBXESJrtAyG6jg14rPEx3V5VnE18rl+Mr4UVxwP1PBwybKHk9/80Snk7IKd/sPTS8oapcSxZGHoCk+y7I70b18YrS0kX0n0Qfo8Aa1CRDV4imoDG1+wziytT+t/hAOx/BZ5bTqw4=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: postgres-users
      namespace: default
    type: Opaque

